[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "google-adk>=1.0.0",
    "google-genai>=1.16.1",
    "graphviz>=0.20.3",
    "litellm>=1.71.1",
]
